# Generated by Django 6.0.6 on 2026-06-12 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stage', models.CharField(choices=[('prospect', 'Prospect'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='prospect', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='customers.customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stage', '-created_at'], name='deals_stage_1ae84d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='deal_value_non_negative')],
            },
        ),
    ]
